openapi: 3.0.3
info:
  title: Team matches management API
  description: Team matches management API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /match:
    get:
      summary: get all matches
      tags:
        - Matches
      operationId: getMatches
      responses:
        200:
          description: list of all matches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
  /players:
    get:
      summary: get all players
      tags:
        - Players
      operationId: getPlayers
      responses:
        200:
          description: list of all players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
  /teams:
    get:
      summary: get all teams
      tags:
        - Teams
      operationId: getTeams
      responses:
        200:
          description: list of all teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
components:
  schemas:
    Player:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        team:
          type: array
          items:
            $ref: '#/components/schemas/Team'
    Team:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        sponsors:
          type: array
          items:
            $ref: '#/components/schemas/Sponsor'
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'
    Goal:
      type: object
      properties:
        id:
          type: integer
        name:
          type: array
          items:
            $ref: '#/components/schemas/Player'
        goal's time:
          type: integer
    Sponsor:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Match:
      type: object
      properties:
        id:
          type: string
        Home:
          $ref: '#/components/schemas/Team'
        Away:
          $ref: '#/components/schemas/Team'
        Datetime:
          type: string
          format: date-time
        Stadium :
          type : string
        Score:
          $ref: '#/components/schemas/Score'
        Scorer:
          $ref : '#/components/schemas/Scorer'
    Score:
      type: object
      properties:
        id:
          type: integer
        team_a_score:
          type: integer
        team_b_score:
          type: integer
    Scorer:
      type : object
      properties:
        id :
          type : integer
        player:
          $ref:  '#/components/schemas/Player'
        ScoringTime :
          type: integer


